# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SSSTest' do

pod 'SQLite.swift',
git: 'https://github.com/stephencelis/SQLite.swift.git'

pod 'GoogleMaps'

pod 'PKHUD'

pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'


end

target 'SSSTestTests' do

end

target 'SSSTestUITests' do

end

